site_name: twoptb
pages:
        - Home: index.md
        - Installation: install.md
        - User Guide:
                - Data Conversion: 'user_guide/data_conversion.md'
                - Motion Registration: 'user_guide/motionreg.md'
                - ROI Definition: 'user_guide/rois.md'
                - Trace Extraction: 'user_guide/trace_extraction.md'
                - Across Day Analysis: 'user_guide/across_days.md'

theme: readthedocs
